background_opacity: 0.8
cursor:
        style: Block
window: 
        dimensions:
                columns: 0
                lines: 0
        padding:
                x: 0
                y: 0
        dynamic_title: true
        history: 10000
font:
        normal: 
                family: monospace
                style: Regular
        bold: 
                family: monospace
                style: Bold
        italic: 
                family: monospace
                style: Italic
        bold_italic:
                family: monospace
                style: Bold Italic
        size: 12.0

colors: 
        primary:
                background: "#440000"
                foreground: "#ffffff"
        cursor: 
                text: "#000000"
                cursor: "#ffffff"
        selection:
                text: "#000000"
                cursor: "#ffffff"
        matches: 
                text: "#000000"
                cursor: "#ffffff"
        bar: 
                background: "#000000"
                cursor: "#ffffff"
        normal:
                black:   '#1d1f21'
                red:     '#cc6666'
                green:   '#b5bd68'
                yellow:  '#f0c674'
                blue:    '#81a2be'
                magenta: '#b294bb'
                cyan:    '#8abeb7'
                white:   '#c5c8c6'

        bright:
                black:   '#666666'
                red:     '#d54e53'
                green:   '#b9ca4a'
                yellow:  '#e7c547'
                blue:    '#7aa6da'
                magenta: '#c397d8'
                cyan:    '#70c0b1'
                white:   '#eaeaea'

        dim:
                black:   '#131415'
                red:     '#864343'
                green:   '#777c44'
                yellow:  '#9e824c'
                blue:    '#556a7d'
                magenta: '#75617b'
                cyan:    '#5b7d78'
                white:   '#828482'


mouse:
        double_click: { threshold: 300 }
        triple_click: { threshold: 300 }
        hints: 
                program: xdg-open
